#!/usr/bin/env Rscript
library(clusterProfiler)

pdf(file = '{out_path}/enrich.pdf')

anno <- read.table(
  '{anno_file}',
  sep = '\t',
  quote = '',
  col.names = c('gene_id', 'ID', 'Description')
)

term2gene <- anno[c('ID', 'gene_id')]

term2name <- anno[c('ID', 'Description')]

gene_id <- read.table('{DEgenes}')
gene_id <- as.character(gene_id$V1)

go_rich <- enricher(gene = as.character(gene_id),
                    TERM2GENE = term2gene,
                    TERM2NAME = term2name,
                    pvalueCutoff = {pvalueCutoff},
                    pAdjustMethod = '{pAdjustMethod}',
                    qvalueCutoff = {qvalueCutoff})
dotplot(go_rich)
write.table(as.data.frame(go_rich), file= "{out_path}/enrich.xls",
            row.names = F, quote=F, sep='\t')
dev.off()
